_extends: ".github"
repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: troy

  # A short description of the repository that will show up on GitHub
  description: A feature rich bot for Discord servers. Developed in Kotlin.

  # A URL with more information about the repository
  homepage: https://github.com/daksh7011/Troy

  # Either `true` to make the repository private, or `false` to make it public.
  private: false

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: true

  # Updates the default branch for this repository.
  default_branch: develop

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: true

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

# Labels: define labels for Issues and Pull Requests
labels:
  - name: bug
    color: CC0000
  - name: fix
    color: D93F0B
  - name: feature
    color: 0E8A16
  - name: commands
    color: 1D76DB
  - name: ci
    color: 1D76DB
  - name: dependency
    color: 1D76DB
  - name: maintenance
    color: 1D76DB
  - name: major
    color: FBCA04
  - name: minor
    color: FBCA04
  - name: patch
    color: FBCA04
  - name: release
    color: 0052CC
  - name: first-timers-only
    oldname: Help Wanted
